name: panarctic_underice_sunlight
channels:
 - conda-forge
dependencies:
 - python ~=3.10

 ###################################################
 # Imported dependencies and extensions            #
 ###################################################

 - jupyterlab
 - matplotlib
 - cartopy
 - dask
 - xarray
 
